package plan

import (
	"bufio"
	"fmt"
	"io"
	"strings"
)

// WriteSQL renders the plan as an executable psql script. Statements are
// grouped by database in the same order Apply runs them: cluster-level
// statements first (on the connection's default database), then each database
// preceded by a \connect meta-command. Where the engine allows it, each
// database's statements are wrapped in BEGIN/COMMIT, mirroring Apply, so a
// failure leaves that database untouched. The COMMIT comes before the next
// \connect because psql silently drops an open transaction when it reconnects.
// Destructive statements and notes are kept as trailing -- comments.
func WriteSQL(p *Plan, w io.Writer) error {
	bw := bufio.NewWriter(w)
	fmt.Fprintln(bw, "-- Generated by pgroledef plan.")
	fmt.Fprintln(bw, "-- Run with: psql -v ON_ERROR_STOP=1 -f <this file>")
	if p.Empty() {
		fmt.Fprintln(bw, "-- No changes. The database matches the declaration.")
		return bw.Flush()
	}
	atomic := p.Dialect.Atomic()
	if !atomic {
		fmt.Fprintf(bw, "-- %s takes one DDL statement per transaction, so this script has none:\n", p.Dialect.Engine)
		fmt.Fprintln(bw, "-- a failure leaves the statements before it in place. Re-run plan to converge.")
	}
	for _, db := range p.Databases() {
		fmt.Fprintln(bw)
		if db == "" {
			fmt.Fprintln(bw, "-- cluster (current database)")
		} else {
			fmt.Fprintf(bw, "-- %s\n", db)
			fmt.Fprintf(bw, "\\connect %s\n", ident(db))
		}
		if atomic {
			fmt.Fprintln(bw, "BEGIN;")
		}
		for _, s := range p.Statements {
			if s.Database != db {
				continue
			}
			fmt.Fprintf(bw, "%s;", s.SQL)
			if c := statementComment(s); c != "" {
				fmt.Fprintf(bw, "  -- %s", c)
			}
			fmt.Fprintln(bw)
		}
		if atomic {
			fmt.Fprintln(bw, "COMMIT;")
		}
	}
	return bw.Flush()
}

func statementComment(s Statement) string {
	var parts []string
	if s.Destructive {
		parts = append(parts, "destructive")
	}
	if s.Note != "" {
		parts = append(parts, s.Note)
	}
	return strings.Join(parts, ": ")
}
