package plan_test

import (
	"strings"
	"testing"

	"github.com/mirakui/pgroledef/internal/config"
	"github.com/mirakui/pgroledef/internal/plan"
)

func TestWriteSQL(t *testing.T) {
	statements := []plan.Statement{
		{Database: "", SQL: `CREATE ROLE "grp_viewer" WITH NOLOGIN`},
		{Database: "", SQL: `REVOKE "grp_viewer" FROM "app_ro"`, Destructive: true, Note: "membership not declared"},
		{Database: "app", SQL: `GRANT USAGE ON SCHEMA "public" TO "grp_viewer"`},
	}
	wrapped := `-- Generated by pgroledef plan.
-- Run with: psql -v ON_ERROR_STOP=1 -f <this file>

-- cluster (current database)
BEGIN;
CREATE ROLE "grp_viewer" WITH NOLOGIN;
REVOKE "grp_viewer" FROM "app_ro";  -- destructive: membership not declared
COMMIT;

-- app
\connect "app"
BEGIN;
GRANT USAGE ON SCHEMA "public" TO "grp_viewer";
COMMIT;
`
	tests := []struct {
		name    string
		dialect plan.Dialect
		want    string
	}{
		{
			name:    "aurora wraps each database in a transaction",
			dialect: plan.DialectFor(config.EngineAuroraPostgres),
			want:    wrapped,
		},
		{
			// A Plan built without DialectFor must behave like Apply does for
			// it: the zero ApplyMode is per-database transactions.
			name:    "zero dialect defaults to transactions",
			dialect: plan.Dialect{},
			want:    wrapped,
		},
		{
			name:    "dsql opens no transaction and says why",
			dialect: plan.DialectFor(config.EngineDSQL),
			want: `-- Generated by pgroledef plan.
-- Run with: psql -v ON_ERROR_STOP=1 -f <this file>
-- Aurora DSQL takes one DDL statement per transaction, so this script opens no
-- transaction: a failure leaves the statements before it in place. Unlike apply,
-- psql does not retry serialization failures (40001). Re-run plan to converge.

-- cluster (current database)
CREATE ROLE "grp_viewer" WITH NOLOGIN;
REVOKE "grp_viewer" FROM "app_ro";  -- destructive: membership not declared

-- app
\connect "app"
GRANT USAGE ON SCHEMA "public" TO "grp_viewer";
`,
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			p := &plan.Plan{Dialect: tt.dialect, Statements: statements}
			var b strings.Builder
			if err := plan.WriteSQL(p, &b); err != nil {
				t.Fatal(err)
			}
			if got := b.String(); got != tt.want {
				t.Errorf("WriteSQL output mismatch\ngot:\n%s\nwant:\n%s", got, tt.want)
			}
		})
	}
}

func TestWriteSQLEmptyPlan(t *testing.T) {
	var b strings.Builder
	if err := plan.WriteSQL(&plan.Plan{}, &b); err != nil {
		t.Fatal(err)
	}
	got := b.String()
	if !strings.Contains(got, "No changes.") {
		t.Errorf("empty plan should say so:\n%s", got)
	}
	for _, line := range strings.Split(strings.TrimSpace(got), "\n") {
		if !strings.HasPrefix(line, "--") {
			t.Errorf("empty plan must contain comments only, got %q", line)
		}
	}
}
