package plan

import (
	"strings"
	"testing"

	"github.com/mirakui/pgroledef/internal/config"
)

func TestWriteSQL(t *testing.T) {
	p := &Plan{Dialect: DialectFor(config.EngineAuroraPostgres), Statements: []Statement{
		{Database: "", SQL: `CREATE ROLE "grp_viewer" WITH NOLOGIN`},
		{Database: "", SQL: `REVOKE "grp_viewer" FROM "app_ro"`, Destructive: true, Note: "membership not declared"},
		{Database: "app", SQL: `GRANT USAGE ON SCHEMA "public" TO "grp_viewer"`},
	}}
	var b strings.Builder
	if err := WriteSQL(p, &b); err != nil {
		t.Fatal(err)
	}
	got := b.String()
	want := `-- Generated by pgroledef plan.
-- Run with: psql -v ON_ERROR_STOP=1 -f <this file>

-- cluster (current database)
BEGIN;
CREATE ROLE "grp_viewer" WITH NOLOGIN;
REVOKE "grp_viewer" FROM "app_ro";  -- destructive: membership not declared
COMMIT;

-- app
\connect "app"
BEGIN;
GRANT USAGE ON SCHEMA "public" TO "grp_viewer";
COMMIT;
`
	if got != want {
		t.Errorf("WriteSQL output mismatch\ngot:\n%s\nwant:\n%s", got, want)
	}
}

func TestWriteSQLDSQLHasNoTransaction(t *testing.T) {
	p := &Plan{Dialect: DialectFor(config.EngineDSQL), Statements: []Statement{
		{Database: "", SQL: `CREATE ROLE "grp_viewer" WITH NOLOGIN`},
		{Database: "postgres", SQL: `GRANT USAGE ON SCHEMA "public" TO "grp_viewer"`},
	}}
	var b strings.Builder
	if err := WriteSQL(p, &b); err != nil {
		t.Fatal(err)
	}
	got := b.String()
	for _, banned := range []string{"BEGIN;", "COMMIT;"} {
		if strings.Contains(got, banned) {
			t.Errorf("DSQL script must not contain %q (one DDL per transaction):\n%s", banned, got)
		}
	}
	if !strings.Contains(got, "-- dsql takes one DDL statement per transaction") {
		t.Errorf("DSQL script should explain why it has no transaction:\n%s", got)
	}
	if !strings.Contains(got, "CREATE ROLE \"grp_viewer\" WITH NOLOGIN;\n") {
		t.Errorf("output missing the statement:\n%s", got)
	}
}

func TestWriteSQLEmptyPlan(t *testing.T) {
	var b strings.Builder
	if err := WriteSQL(&Plan{}, &b); err != nil {
		t.Fatal(err)
	}
	got := b.String()
	if !strings.Contains(got, "No changes.") {
		t.Errorf("empty plan should say so:\n%s", got)
	}
	for _, line := range strings.Split(strings.TrimSpace(got), "\n") {
		if !strings.HasPrefix(line, "--") {
			t.Errorf("empty plan must contain comments only, got %q", line)
		}
	}
}
